// Regenerates packages/server/src/embedded.ts from the built frontend
// (packages/web/dist). Each asset becomes a `with { type: "file" }` import so
// `bun build --compile` bakes its bytes into the binary; a map exposes them by
// URL path. Run after `vite build` and before compiling. The packaging script
// restores the empty default (committed) afterwards so dev/typecheck stay clean.
//
//   bun run scripts/gen-embed.ts

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const here = import.meta.dir; // packages/server/scripts
const serverSrc = join(here, "..", "src");
const distDir = join(here, "..", "..", "web", "dist");

const TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".gif": "image/gif",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".ttf": "font/ttf",
  ".map": "application/json",
  ".txt": "text/plain; charset=utf-8",
  ".wasm": "application/wasm",
};

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

let files: string[];
try {
  files = walk(distDir).sort();
} catch {
  console.error(
    `[gen-embed] no web build found at ${distDir} — run the web build first`,
  );
  process.exit(1);
}

const lines: string[] = [
  "// AUTO-GENERATED by scripts/gen-embed.ts — do not edit.",
  "// @ts-nocheck",
  "",
];
const entries: string[] = [];

files.forEach((abs, i) => {
  const rel = relative(distDir, abs).split("\\").join("/"); // forward slashes
  const importPath = `../../web/dist/${rel}`;
  const ext = rel.slice(rel.lastIndexOf(".")).toLowerCase();
  const type = TYPES[ext] ?? "application/octet-stream";
  lines.push(`import a${i} from ${JSON.stringify(importPath)} with { type: "file" };`);
  entries.push(
    `  ${JSON.stringify(`/${rel}`)}: { path: a${i}, type: ${JSON.stringify(type)} },`,
  );
});

lines.push(
  "",
  "export interface EmbeddedAsset { path: string; type: string; }",
  "export const EMBEDDED: Record<string, EmbeddedAsset> = {",
  ...entries,
  "};",
  "export const HAS_EMBEDDED = true;",
  "",
);

writeFileSync(join(serverSrc, "embedded.ts"), lines.join("\n"));
console.log(`[gen-embed] embedded ${files.length} files from ${distDir}`);
